apiVersion: apps/v1
kind: Deployment
metadata:
  name: browserless
  namespace: browserless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: browserless
      component: chrome
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: browserless
        component: chrome
    spec:
      containers:
        - env:
            - name: MAX_CONCURRENT_SESSIONS
              value: {{ .Values.browserless.maxConcurrentSessions | quote }}
            - name: TOKEN
              value: {{ .Values.browserless.token | quote }}
          image: ghcr.io/browserless/chrome
          name: browserless-chrome
          ports:
            - containerPort: 3000
              name: app
              protocol: TCP
      restartPolicy: Always
