apiVersion: v1
kind: Service
metadata:
  name: transmission
  namespace: media-center
spec:
  ports:
    - name: web
      port: 9091
      targetPort: 9091
  selector:
    app: media-center
    component: transmission
---
apiVersion: v1
kind: Service
metadata:
  name: transmission
  namespace: media-center
spec:
  type: NodePort
  ports:
    - name: tcp-51413
      port: 51413
      targetPort: 51413
      nodePort: 32013
    - name: udp-51413
      port: 51413
      protocol: UDP
      targetPort: 51413
      nodePort: 32013
  selector:
    app: media-center
    component: transmission