apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aria2ng-web
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
    - host: aria.opti.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aria2ng-web
                port:
                  number: 6880
          - path: /jsonrpc
            pathType: Prefix
            backend:
              service:
                name: aria2pro-rpc
                port:
                  number: 6800