apiVersion: v1
kind: PersistentVolume
metadata:
  name: aria2pro-config-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: '{{ .Values.nfs.data.path }}'
    server: '{{ .Values.nfs.data.server }}'

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: aria2pro-downloads-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  nfs:
    path: '{{ .Values.nfs.downloads.path }}'
    server: '{{ .Values.nfs.downloads.server }}'
