apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aria2pro-config-pvc
spec:
  volumeName: aria2pro-config-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aria2pro-downloads-pvc
spec:
  volumeName: aria2pro-downloads-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
