apiVersion: v1
kind: PersistentVolume
metadata:
  name: qinglong-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: '/mnt/data/qinglong-data'
    server: 'nfser'