apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: downloader-ingress
  namespace: media-center
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: qb.opti.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qbittorrent-web
                port:
                  number: 8080
    - host: tr.opti.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: transmission-web
                port:
                  number: 9091