apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-web
  namespace: media-center
spec:
  ports:
    - name: web
      port: 8080
      targetPort: 8080
  selector:
    app: media-center
    component: qbittorrent
