apiVersion: v1
kind: Service
metadata:
  name: transmission-web
  namespace: media-center
spec:
  ports:
    - name: web
      port: 9091
      targetPort: 9091
  selector:
    app: media-center
    component: transmission