apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  db:
    vendor: postgres
    usernameSecret:
      name: usernameSecret
      key: usernameSecretKey
    passwordSecret:
      name: passwordSecret
      key: passwordSecretKey
    host: postgres-postgresql.postgres.svc.cluster.local
    database: keycloak
    port: 5432
    poolInitialSize: 1
    poolMinSize: 1
    poolMaxSize: 3
  http:
    httpEnabled: true
    tlsSecret: keycloak-tls-secret
  hostname:
    hostname: auth.opti.io
    strict: false
    strictBackchannel: false
