apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-cluster-pv1
spec:
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/data/mysql-cluster1
    server: nfser
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-cluster-pv2
spec:
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/data/mysql-cluster2
    server: nfser
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-cluster-pv3
spec:
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/data/mysql-cluster3
    server: nfser
