# Default values for ldap-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

image:
  repository: osixia/openldap
  pullPolicy: IfNotPresent
  tag: "1.5.0"

service:
  type: NodePort
  port: 389

env:
  LDAP_ORGANISATION: "MyOrg"
  LDAP_DOMAIN: "myorg.com"
  LDAP_ADMIN_PASSWORD: "adminpassword"

persistence:
  enabled: true
  storageClass: "nfs-client"
  accessMode: "ReadWriteOnce"
  size: "1Gi"

phpLDAPadmin:
  enabled: true
  image:
    repository: osixia/phpldapadmin
    tag: "0.9.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    hosts:
      - host: ldap.opti.io
        paths:
          - path: /
            pathType: ImplementationSpecific

