apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: media-center-ingress
  namespace: media-center
spec:
  rules:
    - host: bazarr.opti.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bazarr
                port:
                  name: app
    - host: emby.opti.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: emby
                port:
                  name: app
    - host: flexget.opti.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flexget
                port:
                  name: app
    - host: prowlarr.opti.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prowlarr
                port:
                  name: app
    - host: radarr.opti.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: radarr
                port:
                  name: app
    - host: sonarr.opti.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sonarr
                port:
                  name: app
    - host: whisparr.opti.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whisparr
                port:
                  name: app

    - host: overseerr.opti.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: overseerr
                port:
                  name: app
