apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-center-pv
spec:
  capacity:
    storage: 51200Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: '{{ .Values.nfs.media.path }}'
    server: '{{ .Values.nfs.media.server }}'

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-center-sonarr-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: '{{ .Values.nfs.data.path }}/sonarr'
    server: '{{ .Values.nfs.data.server }}'

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-center-radarr-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: '{{ .Values.nfs.data.path }}/radarr'
    server: '{{ .Values.nfs.data.server }}'

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-center-prowlarr-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: '{{ .Values.nfs.data.path }}/prowlarr'
    server: '{{ .Values.nfs.data.server }}'

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-center-emby-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: '{{ .Values.nfs.data.path }}/emby'
    server: '{{ .Values.nfs.data.server }}'

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-center-searcharr-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: '{{ .Values.nfs.data.path }}/searcharr/data'
    server: '{{ .Values.nfs.data.server }}'

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-center-bazarr-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: '{{ .Values.nfs.data.path }}/bazarr'
    server: '{{ .Values.nfs.data.server }}'

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-center-flexget-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: '{{ .Values.nfs.data.path }}/flexget/config'
    server: '{{ .Values.nfs.data.server }}'

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-center-flexget-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: '{{ .Values.nfs.data.path }}/flexget/data'
    server: '{{ .Values.nfs.data.server }}'
