---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: media-center
    component: bazarr
  name: bazarr
  namespace: media-center
spec:
  ports:
    - name: app
      port: 6767
      targetPort: 6767
  selector:
    app: media-center
    component: bazarr
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: media-center
    component: emby
  name: emby
  namespace: media-center
spec:
  ports:
    - name: app
      port: 8096
      targetPort: 8096
  selector:
    app: media-center
    component: emby
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: media-center
    component: emby
  name: emby-direct
  namespace: media-center
spec:
  ports:
    - name: app
      port: 8096
      targetPort: 8096
      nodePort: 32096
  type: NodePort
  selector:
    app: media-center
    component: emby
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: media-center
    component: flexget
  name: flexget
  namespace: media-center
spec:
  ports:
    - name: app
      port: 5050
      targetPort: 5050
  selector:
    app: media-center
    component: flexget

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: media-center
    component: prowlarr
  name: prowlarr
  namespace: media-center
spec:
  ports:
    - name: app
      port: 9696
      targetPort: 9696
  selector:
    app: media-center
    component: prowlarr

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: media-center
    component: radarr
  name: radarr
  namespace: media-center
spec:
  ports:
    - name: app
      port: 7878
      targetPort: 7878
  selector:
    app: media-center
    component: radarr

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: media-center
    component: sonarr
  name: sonarr
  namespace: media-center
spec:
  ports:
    - name: app
      port: 8989
      targetPort: 8989
  selector:
    app: media-center
    component: sonarr

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: media-center
    component: whisparr
  name: whisparr
  namespace: media-center
spec:
  ports:
    - name: app
      port: 6969
      targetPort: 6969
  selector:
    app: media-center
    component: whisparr

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: media-center
    component: overseerr
  name: overseerr
  namespace: media-center
spec:
  ports:
    - name: app
      port: 5055
      targetPort: 5055
  selector:
    app: media-center
    component: overseerr