apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ddns-go-web
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: ddns.opti.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ddns-go-web
                port:
                  number: 9876
