apiVersion: v1
kind: PersistentVolume
metadata:
  name: ddns-config-pv
spec:
  capacity:
    storage: 1M
  accessModes:
    - ReadWriteOnce
  nfs:
    path: '/mnt/data/ddns-go-config'
    server: 'nfser'