apiVersion: v1
kind: Service
metadata:
  name: {{ include "wakapi.fullname" . }}
  labels:
    {{- include "wakapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "wakapi.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wakapi.fullname" . }}-loadbalancer
  labels:
    {{- include "wakapi.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - name: external
      port: {{ .Values.service.loadBalancerPort }}
      protocol: TCP
      targetPort: http

  selector:
    {{- include "wakapi.selectorLabels" . | nindent 4 }}