apiVersion: v1
kind: Service
metadata:
  name: metabase
  namespace: metabase
spec:
  ports:
    - name: app
      port: 3000
      targetPort: 3000
  selector:
    app: metabase
    component: metabase
