apiVersion: v1
kind: PersistentVolume
metadata:
  name: asf-config-pv
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: '{{ .Values.nfs.config.path }}'
    server: '{{ .Values.nfs.config.server }}'
